version: "3"
volumes:
  abc:
    driver: local

services:
  db:
    image: mariadb:11.2.2-jammy
    container_name: db
    environment:
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_DATABASE=demo
      - MARIADB_USER=user01
      - MARIADB_PASSWORD=pass
    volumes:
      - ./db/table.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2.sql

  go:
    build: 
      context: ./demo-go
      dockerfile: Dockerfile
    image: mygo:5.0
    ports:
      - 1323:1323
  react:
    build: 
      context: ./demo-react
      dockerfile: Dockerfile
    image: myreact:5.0
    ports:
      - 9999:80
    